# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'My Corneish Zen'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '[
        "corneish_zen_v2_left","corneish_zen_v2_right"
      ]'
      alphas: '["qwerty"]'
      nav: '["vi"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      clipboard: '["mac"]'
      branches: '["zmkfirmware/zmk/main urob/zmk/mouse-3.2"]'
